CREATE TABLE IF NOT EXISTS feeds (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  pubdate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  isodate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  link TEXT NOT NULL,
  contentsnippet TEXT NOT NULL,
  content TEXT NOT NULL,
  author TEXT NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  author_id INTEGER REFERENCES authors(id) ON DELETE CASCADE,
  book_id INTEGER REFERENCES books(id) ON DELETE CASCADE
);
