CREATE TABLE IF NOT EXISTS feeds (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  pubdate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  isodate TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  link TEXT NOT NULL,
  contentsnippet TEXT NOT NULL,
  content TEXT NOT NULL,
  author TEXT NOT NULL
);
